services:
  - type: web
    name: abraava-bot
    env: docker
    plan: free
    region: ohio
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        value: 1011430416:Ur740PtSXvB3cIiA6ZfRzQLKPYLnBnYhy8w
      - key: DB_CHANNEL_ID
        value: ""
      - key: INFO_CHANNEL_ID
        value: abraava
      - key: API_BASE_URL
        value: https://3rah.ir/users/index.php
      - key: API_TOKEN
        sync: false
      - key: PORT
        value: 8080
      - key: PLATFORM
        value: bale
